---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/component: config
    app.kubernetes.io/name: keycloak-broker
  name: {{ .Release.Name }}
type: Opaque
data:
  PORT: {{ .Values.broker.configuration.port | b64enc }}
  BROKER_LOG_LEVEL: {{ .Values.broker.configuration.log_level | b64enc }}
  BROKER_LOG_TIMESTAMP: {{ .Values.broker.configuration.log_timestamp | b64enc }}
  BROKER_USERNAME: {{ .Values.broker.configuration.username | b64enc }}
  BROKER_PASSWORD: {{ .Values.broker.configuration.password | b64enc }}
  KEYCLOAK_URL: {{ .Values.keycloak.configuration.url | b64enc }}
  KEYCLOAK_REALM: {{ .Values.keycloak.configuration.realm | b64enc }}
  KEYCLOAK_ADMIN: {{ .Values.keycloak.configuration.admin | b64enc }}
  KEYCLOAK_PASSWORD: {{ .Values.keycloak.configuration.password | b64enc }}

{{ if and .Values.broker.image.pullSecret.username .Values.broker.image.pullSecret.password -}}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/component: registry
    app.kubernetes.io/name: keycloak-broker
  name: {{ .Release.Name }}-registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{ end }}
