---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/component: svc
    app.kubernetes.io/name: keycloak-broker
  name: {{ .Release.Name }}
spec:
  ports:
  - port: {{ .Values.broker.configuration.port }}
    name: web
    protocol: TCP
    targetPort: {{ .Values.broker.configuration.port }}
  selector:
    app: {{ .Release.Name }}
    app.kubernetes.io/component: app
    app.kubernetes.io/name: keycloak-broker
  type: ClusterIP
